### ISSUE TITLE
Hi, the data of N-S equation is missing, could you please upload this file?

### ISSUE THREAD

**Issue by ajogajog** [snagcliffs/PDE-FIND#3]

**Comment by ajogajog** [comment]
in Examples/Navier-Stokes with noise.ipynb,  line data = sio.loadmat('../CYLINDER/DATA/ALL.mat') the ALL.mat is missing. Could you please upload this file?

**Comment by snagcliffs** [comment]
Hi, that dataset is too large to put on github.  Code for generating it is here, https://github.com/cwrowley/ibpm

**Comment by ajogajog** [comment]
thank you very much!

**Comment by kevinegan31** [comment]
I'm able to run ibpm from https://github.com/cwrowley/ibpm, but does that code create the "ALL.mat" file used in the N-S code? I see ibpm00200.plt, ibpm00100.plt, and ibpm00000.plt created from running the commands.

**Comment by Jack36lee** [comment]
Hello, I tried ibpm from [https://github.com/cwrowley/ibpm] and also goes to the same timesteps given in  Examples/Navier-Stokes, but my output seems to be symmetrical, totally different from the picture shown in Examples/Navier-Stokes. 
![Figure 2021-01-14 202432](https://user-images.githubusercontent.com/77443155/104590860-e1ee9000-56a6-11eb-9751-3a162d21f9f0.png)

I have tried to change the ibpm options but always get the symmetrical results. Could do please show the ibpm options? So that the asymmetric results can get. Thank you very much!

**Comment by snagcliffs** [comment]
Jack, I added a few files to the datasets folder to help run the IBPM code.  Since the initial condition is symmetric, you'd need to wait for numerical error to introduce asymmetry to get vortex shedding, which can take a while.  Placing datasets/von_karman in your ibpm folder and running von_karman.sh will start the simulation from an IC which avoids this and should give you the correct dataset.

Kevin, sorry for not replying to your question last year.  There is a notebook in datasets/von_karman which loads the ibpm output files into python and can replace the line loading ALL.mat, which was made using similar code in matlab.  It might be best to save U, V, and W as numpy arrays to reduce the load time for future use.

**Comment by Jack36lee** [comment]
Thank you very much! I successfully run it by using the initial condition on the von_karman folder. Also, when I set the timesteps very large (e.g. 15000 or 20000), it gave a similar result, asymmetry vortex shedding. Thanks again!
